debug = true

logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[api]
address = ":8080"
  [api.auth.basic]
  users = ["test:$apr1$iT82Z453$soPTsIhDKjBq9Yy9BTB0U/"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sendthebricks.com"
watch = true
exposedByDefault = false


[acme]
email = "seriousfunk@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[acme.httpChallenge]
entryPoint = "http"

